### ISSUE TITLE
Crash when rebuilding in WSL after using Windows Terminal

### ISSUE THREAD

**Issue by SuperSandro2000** [maralorn/nix-output-monitor#10]
I am not sure why this happens but it ends the ``home-manager switch``. After successfully executing it from Windows Terminal it works again.

![image](https://user-images.githubusercontent.com/7258858/96453585-f5f73280-121a-11eb-8668-aebf8091e3eb.png)

**Comment by maralorn** [comment]
Can you elaborate a bit more on what you did in what order?

I have zero experience with WSL and Windows Terminal and might just be confused about the parts involved here.

I understand WSL is a way to run linux commands? Is windows terminal the terminal emulator or the shell? When does nom work in Windows Terminal and when doesn‘t it?

**Comment by SuperSandro2000** [comment]
> I understand WSL is a way to run linux commands?

WSL 1 is a tiny VM comparable to WINE but a bit different.

> Is windows terminal the terminal emulator or the shell?

Windows Terminal is the terminal emulator. It supports more settings, tabs and properly emojis. Comparable to Konsole vs XTerm.

> When does nom work in Windows Terminal and when doesn‘t it?

I have no clue. Sometimes it does and sometimes it doesn't.

**Comment by maralorn** [comment]
Okay, so I am not sure I can do anything about this. The error seems to occur in the first moment when nom actually tries to print it's own output. And in this moment while trying to write to stdout it get's an invalid character warning. So maybe the terminal is not unicode capable in that moment or rather expects another encoding than utf-8? Or maybe it trips over the color codes? Or the cursor movement codes? Who knows … Encoding is hard …

Someone could try to triage this by running different versions of the code with those features enabled or disabled. If we know what the reason is maybe we can just fix it. Or we write a detection for a terminal betraying us and then falling back to not using the feature we suspect to be the culprit.

**Comment by SuperSandro2000** [comment]
It can't be scrolling because that is catched by the window directly and no escape codes are send AFAIK.

**Comment by SuperSandro2000** [comment]
Since then this crash never happened again and I have no plan how to reproduce it. Should we close this issue?
