### ISSUE TITLE
blue foreground on black background can't be read 

### ISSUE THREAD

**Issue by novoid** [maralorn/nix-output-monitor#113]
Hi,

I'm having a white on black terminal [setup](https://github.com/novoid/nixos-config).

As you can see in the screenshot, blue text is not readable:

![2023-09-17T17 13 54 nh with blue foreground on black background -- screenshots](https://github.com/viperML/nh/assets/727493/3e62a073-c670-4a84-a492-b0383d9e263c)

Maybe you can think of a solution here that doesn't involve switching to a bright color theme?

**Comment by maralorn** [comment]
In my opinion it is the responsibility of the terminal theme to guarantee a good contrast between the colors offered.
This blue tone is not hardcode in nom it is the default blue configured in your terminal.
I assume most users use nom in dark mode, I do too.

![image](https://github.com/maralorn/nix-output-monitor/assets/1651325/2476ce5f-9535-460d-8229-0f45e0c02297)

As you can see I even have blue on blue there, but because the terminal colors are very bright the dark background is not a problem.

I am open to suggestions but I wouldn’t know what else to do. nom restricts itself to use the 8 default colors available in the terminal so that it correctly adapts to the user color theme.

**Comment by novoid** [comment]
Thanks for your explanation and your screenshot.

I'm using xfce4-terminal with its default (dark) settings. I switched the setting for blue (Edit - Preferences - Colors - Palette) to a brighter one which fixes the issue for me. Maybe the xfce4-terminal defaults are causing this issue. For nom, this is solved, thanks.
