### ISSUE TITLE
progress indications for build systems which provide that

### ISSUE THREAD

**Issue by expipiplus1** [maralorn/nix-output-monitor#12]
It would be a nice trick to report progress for builds which report it in their stderr:

Some examples from builds I have running currently:

- ` 11% [=======----------------------------------------------------(B](B ETA: 00:00:48` -- gnutest?
  - Just test phase
- `[ 83%] Built target MITests` -- cmake
- `[ 2 of 13] Compiling Text.Trifecta.Util.IntervalMap ( src/Text/Trifecta/Util/IntervalMap.hs, dist/build/Text/Trifecta/Util/IntervalMap.o )` -- cabal 
  - Just that component (and repeated due to profiling builds)

Obviously this isn't going to be perfect, but is it better than nothing? I'm a little undecided. CMake (and bazel I think) do this quite well, but cabal's per-component reporting is probably not worth it.

(Hitting `enter` in the title text entry opens the issue!, I'll be filling that out last from now on, sorry for the email demanding "progress" :laughing:)

**Comment by maralorn** [comment]
Thank you for that idea!

I'll need to think about it for a while. Right now I don‘t think that is feasible. The problem is, that when multiple builds are running there is no way to tell which build a specific output belongs to.

I mean it would be a great start if we could capture for every build in which stdenv phase it is in right now, but same problem.

**Comment by expipiplus1** [comment]
Oh of course! I didn't consider that, that makes it much harder.
