### ISSUE TITLE
Load average

### ISSUE THREAD

**Issue by expipiplus1** [maralorn/nix-output-monitor#15]
It would be nice to have a system load indication.

There's plenty of space left in the bottom row of stats, however this would risk cluttering it a little.

**Comment by maralorn** [comment]
Hm, where do we start, where do we stop?
How easy is this to detect crossplattform?
Memory usage would also be interesting, I guess?
(Maybe only display a warning, when memory is nearly full?)

I am definitely open to the idea though. But of course we don‘t want to reimplement htop, which users always can open in a second tab.

**Comment by maralorn** [comment]
As an explanation: I decided to not tackle this because I think

a) terminal screen real estate is a scarce resource and
b) I wouldn‘t know how easy it is to implement this platform independently.
c) I assume most users have a way to see their load average quickly in some other way, when they need it.

**Comment by expipiplus1** [comment]
Understandable! happy to close
