### ISSUE TITLE
hermes-json portability

### ISSUE THREAD

**Issue by alyssais** [maralorn/nix-output-monitor#79]
Quoting the [hermes-json documentation](https://hackage.haskell.org/package/hermes-json):

> ## Portability
>
> Per the simdjson documentation:
> A recent compiler (LLVM clang6 or better, GNU GCC 7.4 or better, Xcode 11 or better) on a 64-bit (PPC, ARM or x64 Intel/AMD) POSIX systems such as macOS, freeBSD or Linux. We require that the compiler supports the C++11 standard or better.
However, this library relies on std::string_view without a shim, so C++17 or better is highly recommended.

Would it be possible to support a different JSON library, for other architectures (32-bit or e.g. RISC-V)?  Alternatively, does nix-output-monitor need very high performance JSON decoding where available, or would it make sense to switch entirely to a more portable (if less performant) library?

**Comment by maralorn** [comment]
Oh, Sorry, I certainly read that when migrating to hermes-json. I just didn’t consider that anyone would want to use this on an unsupported platform.

nom had been using aeson before and that was the biggest performance problem in my benchmarks. Migrating back to aeson or another Haskell native binary might introduce a bit more flickering, but would certainly be acceptable, at least on the platforms that hermes-json does not support. Otoh I think a convenience tool like nom should strive to be as performant as possible to save energy and because people need their cycles to run their actual builds.

The aeson code was removed in [626001a] I assume that I wouldn’t be too hard to revive it, but the code structure changed a bit since then.

I am open to any solution to this problem which increases portability without sacrificing performance significantly. It certainly can be done. nom has enough tests and benchmarks to evaluate a change like that easily.

I would start by evaluating available json libraries (or more general parser) libraries and see which solution would give the most performance while still being Haskell native.

Sadly, I don’t have time to work on this in the next few months.

**Comment by alyssais** [comment]
Sorry, false alarm!  Upon further investigation, it turns out that despite printing a compiler error(?), hermes-json _does_ build on these platforms, and the actual build failure I was seeing was a test failure due to use of a >32-bit number.  So, assuming that nom won't be decoding numbers that big, I think all that's required will be to disable the tests for hermes-json in Nixpkgs.
