### ISSUE TITLE
Emojis in WSL

### ISSUE THREAD

**Issue by SuperSandro2000** [maralorn/nix-output-monitor#9]
Follow up to #6

I am running WSL in Windows Terminal Preview and this happens:

![image](https://user-images.githubusercontent.com/7258858/96444371-75cad000-120e-11eb-8b7d-25171e16c491.png)

**Comment by maralorn** [comment]
Okay, this is getting tricky. Apparently in the font used there the `bold Sigma` or the the `play` symbol are wider than expected.
At least the play symbol is supposed to be positioned below the B of Builds.

It's a bit strange though, since both characters sure look like they are exactly one character wide and there is just a space too much in between. Can you get insight into that by selecting them?

Anyways, if this is about diverging emoji widths at this point we could

a) invest half a year of getting a solid understanding of unicode emojis and all implementation artifacts
b) let the user give a config file were they can give an emoji and tell it's width.
c) provide a fallback mode where we replace all emojis with letters.
d) any combination of the above.

I can not promise that I will invest work into this. But I would be open to any good alternatives, suggestions or (of course) PRs.

**Comment by SuperSandro2000** [comment]
BTW I am using a Nerd Fonts patched with JetBrains Mono on this machine.

> Can you get insight into that by selecting them?

Each symbol is one selection and after the sigma there are two spaces.

maybe just use UTF8 characters which do not behave that strangely.

**Comment by maralorn** [comment]
> BTW I am using a Nerd Fonts patched with JetBrains Mono on this machine.
> 
> > Can you get insight into that by selecting them?
> 
> Each symbol is one selection and after the sigma there are two spaces.

Hugh, I will stare at my code for a few moments to figure out if the two spaces could have come from anywhere.

> maybe just use UTF8 characters which do not behave that strangely.

I am totally open to that idea. But how do I know which characters are sane and which aren‘t? The hourglass already seemed kinda crazy to me. Apparently testing them on my system is not enough.

**Comment by SuperSandro2000** [comment]
> But how do I know which characters are sane and which aren‘t?

You could maybe test it by setting LC_LANG=C?

**Comment by maralorn** [comment]
I have completely refactored the printing code this includes code to better deal with different icon widths of emojis. Let me know if this issue still persists.

**Comment by SuperSandro2000** [comment]
Still looking off in Windows Terminal.

![image](https://user-images.githubusercontent.com/7258858/108618345-948bde00-741d-11eb-8d5c-fb002b54996d.png)

**Comment by maralorn** [comment]
I have pushed a branch `bigsum` which replaces the sigma with another symbol which is better suited anyways.

Would you be able to test that branch?

**Comment by SuperSandro2000** [comment]
Looks solved:
![image](https://user-images.githubusercontent.com/7258858/109168814-7ad0fa80-777f-11eb-8084-b9c2a55e3366.png)
